apiVersion: v1 #Version
kind: Pod #Type of Object
metadata:
    name: client-pod
    labels:
      component: web
spec:
    containers:
      - name: client
        image: stephengrider/multi-client
        ports:
          - containerPort: 3000
# kubectl apply -f client-pod.yaml = configure pod/client-pod inside local VM from minkube start command = running container