apiVersion: v1 #Version
kind: Service #Type of Object
metadata:
    name: client-node-port
spec:
    type: NodePort
    ports:
        - ports: 3050
          targetPort: 3000
          nodePort: 31515
    selector:
        componenet: web
